#!/usr/bin/env bash

declare -a FILES

while (( $# > 0 )); do
	if [[ -d "$1" ]]; then
		mapfile -d $'\0' FILES_ADD < <(find "$1" -mindepth 1 -maxdepth 1 -print0 -type f)
		FILES+=("${FILES_ADD[@]}")
	else
		FILES+=("$1")
	fi
	shift
done

set -- "${FILES[@]}"

FIFO=$(mktemp -u --tmpdir${XDG_RUNTIME_DIR:+=$XDG_RUNTIME_DIR} "$$-XXXX")
mkfifo "$FIFO"

tail -f "$FIFO" | zenity --progress --auto-close --auto-kill --width=500 &

TEXT=$(
	i=0
	for f in "$@"; do
		echo "$((i*100/$#))" >> "$FIFO"
		echo "# $f" >> "$FIFO"
		ffprobe -v quiet -of csv=p=0 -show_entries format=duration "$f"
		i=$((i+1))
	done | awk '{sum += $1}; END{printf "%dh %dm %ds\n", sum/3600, sum%3600/60, sum%60}'
)

echo 100 >> "$FIFO"

rm -f "$FIFO"
zenity --info --title="Total duration" --text="$TEXT"
